#APP deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: k8s-app
        envFrom:
        - configMapRef:
            name: k8s-app-configmap
        env:
        - name: APP_DB_USER
          value: user
        - name: APP_DB_HOST
          value: k8s-mysql
        - name: APP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: k8s-app
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
