#DB deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mysql
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password 
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: k8s-mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: k8s-mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pv-storage
